//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderId { get; set; }
        public int userId { get; set; }
        public System.DateTime orderTime { get; set; }
        public string billingAddress { get; set; }
        public string transactionType { get; set; }
        public int courseId { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual User User { get; set; }
    }
}
