//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int replyId { get; set; }
        public int postId { get; set; }
        public System.DateTime replyTime { get; set; }
        public int userId { get; set; }
        public string replyText { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
